apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payment-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wallet-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: wallet-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ledger-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ledger-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gateway-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-service
